
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.util.StringTokenizer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class categorypanels extends javax.swing.JPanel {

    /**
     * Creates new form categorypanels
     */
    public categorypanels() {
        initComponents();
        setSize(800,200);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbcategoryname = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainpanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        setLayout(null);

        lbcategoryname.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbcategoryname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbcategoryname.setText("jLabel1");
        add(lbcategoryname);
        lbcategoryname.setBounds(20, 10, 590, 60);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(32767, 32767));

        mainpanel.setBackground(new java.awt.Color(102, 255, 204));
        mainpanel.setLayout(null);
        jScrollPane1.setViewportView(mainpanel);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 630, 180);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lbcategoryname;
    public javax.swing.JPanel mainpanel;
    // End of variables declaration//GEN-END:variables

    
    
}
