/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class roompanel extends javax.swing.JPanel {

    /**
     * Creates new form roompanel
     */
    public roompanel() {
        initComponents();
        setSize(200,200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbpreview = new javax.swing.JLabel();
        lbroomname = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(null);

        lbpreview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbpreview);
        lbpreview.setBounds(20, 10, 170, 130);

        lbroomname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add(lbroomname);
        lbroomname.setBounds(10, 160, 180, 50);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lbpreview;
    public javax.swing.JLabel lbroomname;
    // End of variables declaration//GEN-END:variables
}
