
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Hp
 */
public class userchangepassword extends javax.swing.JFrame {

    /**
     * Creates new form userchangepassword
     */
   

    userchangepassword() {
        initComponents();
        setSize(600, 600);
       getContentPane().setBackground(new java.awt.Color(153, 255, 204));
        tfusername.setText(GlobalData.nameofuser);
        tfusername.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        tfoldpassword = new javax.swing.JTextField();
        pfnewpass = new javax.swing.JPasswordField();
        pfconpass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Change Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 20, 470, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 110, 110, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Oldpassword");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 170, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("New Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 220, 170, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Confirm Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 280, 180, 30);
        getContentPane().add(tfusername);
        tfusername.setBounds(260, 110, 190, 40);
        getContentPane().add(tfoldpassword);
        tfoldpassword.setBounds(260, 166, 190, 40);
        getContentPane().add(pfnewpass);
        pfnewpass.setBounds(256, 220, 190, 40);
        getContentPane().add(pfconpass);
        pfconpass.setBounds(260, 270, 190, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Change Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 340, 190, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String un = tfusername.getText();
        String oldpass = tfoldpassword.getText();
        String newpass = pfnewpass.getText();
        String conpass = pfconpass.getText();
        if (un.equals("") || oldpass.equals("") || newpass.equals("") || conpass.equals("")) {
            JOptionPane.showMessageDialog(this, "All fields are mandatory");
        } else if (!(newpass.equals(conpass))) {
            JOptionPane.showMessageDialog(this, "new and confirm password does not match");
        } else {
            try {
                HttpResponse<String> response = Unirest.get(GlobalData.hostname + "/UserChangePassword")
                        .queryString("username", un)
                        .queryString("oldpassword", oldpass)
                        .queryString("newpassword", newpass)
                        .asString();
                if (response.getStatus() == 200) {
                    JOptionPane.showMessageDialog(this, response.getBody());
                    if (response.getBody().trim().equals("Password Changed Successfully")) {
                        dispose();
                        new userlogin().setVisible(true);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, response.getStatusText());
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userchangepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userchangepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userchangepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userchangepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new userchangepassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField pfconpass;
    private javax.swing.JPasswordField pfnewpass;
    private javax.swing.JTextField tfoldpassword;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables
}
