
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author DELL
 */
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;

import javax.swing.plaf.basic.BasicTextFieldUI;
import javax.swing.text.JTextComponent;


 
public class Add_Customer extends javax.swing.JInternalFrame {

    /**
     * Creates new form Add_Customer
     */
    static Connection con;

    public Add_Customer(Connection con) {
        initComponents();
        this.con = con;
        search_txt.setUI(new HintTextFieldUI("Search", true));
        delete_btn.setVisible(false);
        submit_btn.setText("Submit");
        show_customer_details();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_custome_panel = new javax.swing.JPanel();
        customer_details_panel = new javax.swing.JPanel();
        address_label = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        name_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address_txt_area = new javax.swing.JTextArea();
        contact_label = new javax.swing.JLabel();
        contact_txt = new javax.swing.JTextField();
        other_contact_label = new javax.swing.JLabel();
        other_contact_txt = new javax.swing.JTextField();
        delete_btn = new javax.swing.JButton();
        submit_btn = new javax.swing.JButton();
        email_label = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        reset_btn = new javax.swing.JButton();
        view_customer_scrollpane = new javax.swing.JScrollPane();
        view_customer_table = new javax.swing.JTable();
        search_txt = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        add_customer_label = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add_custome_panel.setBackground(new java.awt.Color(255, 153, 0));
        add_custome_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customer_details_panel.setBackground(new java.awt.Color(153, 153, 0));
        customer_details_panel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        customer_details_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        address_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        address_label.setText("Address");
        customer_details_panel.add(address_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txtActionPerformed(evt);
            }
        });
        customer_details_panel.add(name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 440, 30));

        name_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        name_label.setText("Name");
        customer_details_panel.add(name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        address_txt_area.setColumns(20);
        address_txt_area.setRows(5);
        jScrollPane1.setViewportView(address_txt_area);

        customer_details_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 440, -1));

        contact_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        contact_label.setText("Contact No.");
        customer_details_panel.add(contact_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));
        customer_details_panel.add(contact_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 440, 30));

        other_contact_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        other_contact_label.setText("Other Contact No. (if any)");
        customer_details_panel.add(other_contact_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));
        customer_details_panel.add(other_contact_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 440, 30));

        delete_btn.setBackground(new java.awt.Color(0, 0, 204));
        delete_btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(255, 255, 255));
        delete_btn.setText("Delete");
        delete_btn.setBorder(null);
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        customer_details_panel.add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, 80, 30));

        submit_btn.setBackground(new java.awt.Color(0, 0, 204));
        submit_btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        submit_btn.setForeground(new java.awt.Color(255, 255, 255));
        submit_btn.setText("Submit");
        submit_btn.setBorder(null);
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });
        customer_details_panel.add(submit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 80, 30));

        email_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        email_label.setText("E-Mail");
        customer_details_panel.add(email_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));
        customer_details_panel.add(email_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 440, 30));

        reset_btn.setBackground(new java.awt.Color(0, 0, 204));
        reset_btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        reset_btn.setForeground(new java.awt.Color(255, 255, 255));
        reset_btn.setText("Reset");
        reset_btn.setBorder(null);
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        customer_details_panel.add(reset_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 590, 80, 30));

        view_customer_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        view_customer_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                view_customer_tableMouseClicked(evt);
            }
        });
        view_customer_scrollpane.setViewportView(view_customer_table);

        customer_details_panel.add(view_customer_scrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 720, 480));

        search_txt.setBackground(new java.awt.Color(153, 153, 0));
        search_txt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        search_txt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        customer_details_panel.add(search_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 290, 30));

        search_btn.setBackground(new java.awt.Color(0, 0, 204));
        search_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        search_btn.setForeground(new java.awt.Color(255, 255, 255));
        search_btn.setText("Search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        customer_details_panel.add(search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 50, -1, 30));

        add_custome_panel.add(customer_details_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1300, 690));

        add_customer_label.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        add_customer_label.setForeground(new java.awt.Color(255, 255, 255));
        add_customer_label.setText("ADD CUSTOMER DETAILS");
        add_custome_panel.add(add_customer_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        getContentPane().add(add_custome_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public Vector show_data(String search)
{
    String found=search;
     try {
            PreparedStatement ps = con.prepareStatement(query_show);
            if(!found.isEmpty())
            {
                ps.setString(1,found);
            }
            ResultSet rs = ps.executeQuery();
            h = new Vector();
           Vector d = new Vector();
           h.add("S.No.");
            h.add("Name");
            h.add("Address");
            h.add("Contact No.");
            h.add("Other Contact No.");
            h.add("E-mail");
            row=0;
            while (rs.next()) {
                Vector d1=new Vector();
                
                d1.add(rs.getString("serial_id"));
                d1.add(rs.getString("name"));
                d1.add(rs.getString("address"));
                d1.add(rs.getString("contact_no"));
                d1.add(rs.getString("other_contact_no"));
                d1.add(rs.getString("e_mail"));
                d.add(d1);
                row++;
            }
            if(d.isEmpty())
            {
                return null;
            }
            return d;
           // DefaultTableModel dtf=new DefaultTableModel(d,h);
            //view_customer_table.setModel(dtf);
            
        } catch (SQLException ex) {
           return null;
        }
        
}
    public void show_customer_details() {
        query_show = "select * from customer order by serial_id desc";
        Vector d=show_data("");
        
         DefaultTableModel dtf=new DefaultTableModel(d,h);
            view_customer_table.setModel(dtf);
       
       
    }
public void delete_customer_detalis()
{
    String query = "delete from customer where serial_id=?";
            try {
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1,serial_id);
                
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Deleted successfully!");
                ps.close();
            } catch (SQLException ex) {
                Logger.getLogger(Add_Customer.class.getName()).log(Level.SEVERE, null, ex);
            }
        
}
static public void update_customer_details(Connection con)
{
     String query = "update customer set name=?,address=?,contact_no=?,other_contact_no=?,e_mail=? where serial_id=?";
     //System.out.println(name+address+contact_no+other_contact_no+email+serial_id);       
     try {
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, name);
                ps.setString(2, address);
                ps.setString(3, contact_no);
                ps.setString(4, other_contact_no);
                ps.setString(5, email);
                ps.setString(6,serial_id);
                int n = ps.executeUpdate();
               
                ps.close();
            } catch (SQLException ex) {
                Logger.getLogger(Add_Customer.class.getName()).log(Level.SEVERE, null, ex);
            }
}
 static public void submit_customer_details(Connection con)
{
    String query = "insert into customer(name,address,contact_no,other_contact_no,e_mail) values(?,?,?,?,?)";
           
    try {
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, name);
                ps.setString(2, address);
                ps.setString(3, contact_no);
                ps.setString(4, other_contact_no);
                ps.setString(5, email);
                int n = ps.executeUpdate();
                
                ps.close();
            } catch (SQLException ex) {
                Logger.getLogger(Add_Customer.class.getName()).log(Level.SEVERE, null, ex);
            }
}
    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        // TODO add your handling code here:
        
        name = name_txt.getText();
        address = address_txt_area.getText();
        contact_no = contact_txt.getText();
        other_contact_no = other_contact_txt.getText();
        email = email_txt.getText();
        if (name.trim().matches("")) {
            JOptionPane.showMessageDialog(this, "Name Field cannot be empty");
        } else if (address.trim().matches("")) {
            JOptionPane.showMessageDialog(this, "Address Field cannot be empty");
        } else if (contact_no.trim().matches("")) {
            JOptionPane.showMessageDialog(this, "Contact Number Field cannot be empty");
        } else if (email.trim().matches("")) {
            JOptionPane.showMessageDialog(this, "E-mail Field cannot be empty");
        } else {
            if(submit_btn.getText().matches("Submit"))
            {
                submit_customer_details(con);
                JOptionPane.showMessageDialog(this, "Data added successfully!");
            }
            else
            {
                update_customer_details(con);
                JOptionPane.showMessageDialog(this, "Data updated successfully!");
                
            }
            reset_form_fields();
            show_customer_details();
            
            

        }


    }//GEN-LAST:event_submit_btnActionPerformed

    private void view_customer_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_customer_tableMouseClicked
        // TODO add your handling code here:
        int row=view_customer_table.getSelectedRow();
        TableModel tm=view_customer_table.getModel();
        serial_id=(String) tm.getValueAt(row,0);
        name_txt.setText((String) tm.getValueAt(row,1));
        address_txt_area.setText((String) tm.getValueAt(row,2));
        contact_txt.setText((String) tm.getValueAt(row,3));
        other_contact_txt.setText((String) tm.getValueAt(row,4));
        email_txt.setText((String) tm.getValueAt(row,5));
        submit_btn.setText("Update");
        delete_btn.setVisible(true);
        
        
        
    }//GEN-LAST:event_view_customer_tableMouseClicked

    private void name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txtActionPerformed
public void reset_form_fields()
{
     name_txt.setText("");
        address_txt_area.setText("");
        contact_txt.setText("");
        other_contact_txt.setText("");
        email_txt.setText("");
        submit_btn.setText("Submit");
        delete_btn.setVisible(false);
}
    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        // TODO add your handling code here:
        reset_form_fields();
        show_customer_details();
        
        
        
    }//GEN-LAST:event_reset_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        reset_form_fields();
        delete_customer_detalis();
         show_customer_details();
    }//GEN-LAST:event_delete_btnActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        String search_customer=search_txt.getText();
         
          
          //String search=search_txt.getText();
         // System.out.println(search+"hello");
         
        
         if(search_customer.isEmpty())
         {
             JOptionPane.showMessageDialog(this,"Please Enter Something to search!!!");
         }else
         {
             query_show = "select * from customer where name=?";
            Vector d1=show_data(search_customer);
         if(d1==null)
         {
             query_show = "select * from customer where address=?";
             d1=show_data(search_customer);
             System.out.println("sk");
             System.out.println(d1);
             if(d1==null)
             {
                query_show = "select * from customer where e_mail=?";
             d1=show_data(search_customer); 
             System.out.println("sk");
             if(d1==null)
             {
                query_show = "select * from customer where serial_id=?";
                d1=show_data(search_customer);  
                System.out.println("sk"+d1);
             if(d1==null )
             {
                 query_show = "select * from customer where contact_no=?";
                d1=show_data(search_customer); 
                System.out.println("ok");
             if(d1==null )
             {
                 query_show = "select * from customer where other_contact_no=?";
                d1=show_data(search_customer); 
                System.out.println("sk");
                if(d1==null)
                {
                    query_show = "SELECT * FROM customer WHERE name LIKE '"+search_customer+"%'";
                    d1=show_data(""); 
                    System.out.println("sk try"+d1);
                if(d1==null)
                {
                    query_show = "SELECT * FROM customer WHERE address LIKE '"+search_customer+"%'";
                    d1=show_data(""); 
                    if( d1==null)
                    {
                        query_show = "SELECT * FROM customer WHERE e_mail LIKE '"+search_customer+"%'";
                    d1=show_data(""); 
                     if( d1==null)
                    {
                        query_show = "SELECT * FROM customer WHERE contact_no LIKE '"+search_customer+"%'";
                    d1=show_data(""); 
                     if(d1==null )
                    {
                        query_show = "SELECT * FROM customer WHERE other_contact_no LIKE '"+search_customer+"%'";
                    d1=show_data(""); 
                    if(d1==null)
                    {
                        query_show = "SELECT * FROM customer WHERE serial_id LIKE '"+search_customer+"%'";
                        d1=show_data(""); 
                    }
                    }
                    }
                    }
                   
                }
                }
                
              
             }
             }
             }
             }
         }
         
             if(d1==null)
                {
                    JOptionPane.showMessageDialog(this,"No result found!\nTry Again");
                System.out.println("sk");
                }
             else
             {
            DefaultTableModel dtf=new DefaultTableModel(d1,h);
            view_customer_table.setModel(dtf); 
            if(row>1)
            {
            JOptionPane.showMessageDialog(this,row+" rows found!");
            }
            else
            {
                JOptionPane.showMessageDialog(this,row+" row found!");
            }
            System.out.println("k");
         }
         }
         
        
    }//GEN-LAST:event_search_btnActionPerformed
String query_show;
Vector h;
int row=0;
static public String serial_id,name, address, contact_no, other_contact_no, email;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add_custome_panel;
    private javax.swing.JLabel add_customer_label;
    private javax.swing.JLabel address_label;
    private javax.swing.JTextArea address_txt_area;
    private javax.swing.JLabel contact_label;
    private javax.swing.JTextField contact_txt;
    private javax.swing.JPanel customer_details_panel;
    private javax.swing.JButton delete_btn;
    private javax.swing.JLabel email_label;
    private javax.swing.JTextField email_txt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField name_txt;
    private javax.swing.JLabel other_contact_label;
    private javax.swing.JTextField other_contact_txt;
    private javax.swing.JButton reset_btn;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField search_txt;
    private javax.swing.JButton submit_btn;
    private javax.swing.JScrollPane view_customer_scrollpane;
    private javax.swing.JTable view_customer_table;
    // End of variables declaration//GEN-END:variables
}
