
import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Assistant2_login extends javax.swing.JFrame {

    /**
     * Creates new form Assistant2_login
     */
    Connection con;
    public Assistant2_login(Connection con) {
        initComponents();
        this.con=con;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jframe_panel = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        welcome_options_panel = new javax.swing.JPanel();
        supplier_panel = new javax.swing.JPanel();
        supplier_label = new javax.swing.JLabel();
        product_panel = new javax.swing.JPanel();
        product_label = new javax.swing.JLabel();
        welcome_label = new javax.swing.JLabel();
        stock_panel = new javax.swing.JPanel();
        stock_label = new javax.swing.JLabel();
        red_title_panel = new javax.swing.JPanel();
        exit_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1626, 868));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jframe_panel.setPreferredSize(new java.awt.Dimension(1626, 700));
        jframe_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jframe_panel.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 1350, 840));

        welcome_options_panel.setBackground(new java.awt.Color(255, 0, 0));
        welcome_options_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supplier_panel.setBackground(new java.awt.Color(255, 0, 0));
        supplier_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supplier_label.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        supplier_label.setForeground(new java.awt.Color(255, 255, 255));
        supplier_label.setText("Add/View Supplier");
        supplier_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplier_labelMouseClicked(evt);
            }
        });
        supplier_panel.add(supplier_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        welcome_options_panel.add(supplier_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 290, 70));

        product_panel.setBackground(new java.awt.Color(255, 0, 0));
        product_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        product_label.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        product_label.setForeground(new java.awt.Color(255, 255, 255));
        product_label.setText("Add/View Product");
        product_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product_labelMouseClicked(evt);
            }
        });
        product_panel.add(product_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        welcome_options_panel.add(product_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 290, 70));

        welcome_label.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        welcome_label.setForeground(new java.awt.Color(255, 255, 255));
        welcome_label.setText("Welcome");
        welcome_options_panel.add(welcome_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        stock_panel.setBackground(new java.awt.Color(255, 0, 0));
        stock_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stock_label.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        stock_label.setForeground(new java.awt.Color(255, 255, 255));
        stock_label.setText("Add/View Stock");
        stock_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stock_labelMouseClicked(evt);
            }
        });
        stock_panel.add(stock_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        welcome_options_panel.add(stock_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 290, 70));

        jframe_panel.add(welcome_options_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 870));

        red_title_panel.setBackground(new java.awt.Color(51, 153, 0));
        red_title_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exit_label.setText("Log-Out");
        exit_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_labelMouseClicked(evt);
            }
        });
        red_title_panel.add(exit_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 0, 70, 30));

        jframe_panel.add(red_title_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1640, 30));

        getContentPane().add(jframe_panel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void supplier_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_labelMouseClicked
        // TODO add your handling code here:
        supplier_panel.setBackground(new Color(102,255,0));
       stock_panel.setBackground(new Color(255,0,0));
       product_panel.setBackground(new Color(255,0,0));
        jDesktopPane1.removeAll();
        validate();
        Add_supplier add_supplier=new Add_supplier(con);
        add_supplier.setVisible(true);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) add_supplier.getUI()).setNorthPane(null);

        add_supplier.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jDesktopPane1.add(add_supplier);

    }//GEN-LAST:event_supplier_labelMouseClicked

    private void product_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_labelMouseClicked
        // TODO add your handling code here:
          supplier_panel.setBackground(new Color(255,0,0));
       stock_panel.setBackground(new Color(255,0,0));
       product_panel.setBackground(new Color(102,255,0));
        jDesktopPane1.removeAll();
        Add_Product add_Product=new Add_Product(con);
        add_Product.setVisible(true);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) add_Product.getUI()).setNorthPane(null);

        add_Product.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jDesktopPane1.add(add_Product);
        //jDesktopPane1.setSelectedFrame(customer_options);
        //jDesktopPane1.show();

    }//GEN-LAST:event_product_labelMouseClicked

    private void stock_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_labelMouseClicked
        // TODO add your handling code here:
        supplier_panel.setBackground(new Color(255,0,0));
       stock_panel.setBackground(new Color(102,255,0));
       product_panel.setBackground(new Color(255,0,0));
        jDesktopPane1.removeAll();
        Add_stock add_stock=new Add_stock(con);
        add_stock.setVisible(true);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) add_stock.getUI()).setNorthPane(null);

        add_stock.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jDesktopPane1.add(add_stock);
        //jDesktopPane1.setSelectedFrame(customer_options);
        //jDesktopPane1.show();

    }//GEN-LAST:event_stock_labelMouseClicked

    private void exit_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseClicked
        try {
            // TODO add your handling code here:
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Assistant_login.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();

    }//GEN-LAST:event_exit_labelMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit_label;
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jframe_panel;
    private javax.swing.JLabel product_label;
    private javax.swing.JPanel product_panel;
    private javax.swing.JPanel red_title_panel;
    private javax.swing.JLabel stock_label;
    private javax.swing.JPanel stock_panel;
    private javax.swing.JLabel supplier_label;
    private javax.swing.JPanel supplier_panel;
    private javax.swing.JLabel welcome_label;
    private javax.swing.JPanel welcome_options_panel;
    // End of variables declaration//GEN-END:variables
}
