
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.Vector;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
class DrawLine extends JPanel {
    int l;
    public DrawLine(int l)
    {
        this.l=l;
    }
	
	
	
	protected void paintComponent(Graphics g) {
                 Graphics2D g2 = (Graphics2D) g;
                g2.setStroke(new BasicStroke(10));
		g2.setColor( Color.DARK_GRAY);
		// X Start, Y Start, X End, Y End
		// X = <---------->
		g2.drawLine (1,0,1,l+190);
 
	}
}
public class Category extends javax.swing.JInternalFrame {

    /**
     * Creates new form Category
     */
    Connection con;
    public Category(Connection con) {
        initComponents();
        this.con=con;
        category_show();
                  
        }
public void category_show()
{
    //JPanel category_panel=new JPanel();
        //category_panel.setLayout(null);
        //category_panel.setSize(430,290);
       // category_panel.setBackground(Color.yellow);
        
       // category_panel.setVisible(true);
//        JPanel panel=new JPanel();
//        panel.setBackground(Color.blue);
//        category_panel.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,420,20));
//        
        String query="select * from product_brand";
        try {
            PreparedStatement ps=con.prepareStatement(query);
              ResultSet rs=ps.executeQuery();
              int x=0,y=0,y1=0;
              
              
              while(rs.next())
              {
                  //JPanel panel=new JPanel();
                   //  panel.setBackground(Color.blue);
                  JPanel brand_panel=new JPanel();
                  JLabel brand=new JLabel();
                  brand.setFont(new Font("Segoe UI",Font.BOLD,18));
                  brand.setForeground(Color.black);
                  brand.setText(rs.getString("brand_name"));
                  String brand_id=String.valueOf(rs.getInt("brand_id"));
                  //brand.setBounds(20+i,30,80,30);
                  brand_panel.add(brand);
                  //category_panel.remove(panel);
                  category_list_panel.add(brand_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0+x,0,130,30));
                   //category_panel.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,130+i,20));
        
                  System.out.println(20+x);
                 
                  String query1="select * from export_item where brand_id=?";
                   PreparedStatement ps1=con.prepareStatement(query1);
                   ps1.setString(1,brand_id);
                   ResultSet rs1=ps1.executeQuery();
                   y=0;
                   while(rs1.next())
                   {
                     
                    JLabel product=new JLabel();
                  product.setFont(new Font("Segoe UI",Font.PLAIN,18));
                  product.setForeground(Color.green);
                  product.setText(rs1.getString("product_name"));
                 
                  category_list_panel.add(product, new org.netbeans.lib.awtextra.AbsoluteConstraints(10+x,40+y,130,30));
                 
                  y+=50;
                  y1=40+y;
                     
                   }
                    x+=132;
                    if(y1>l)
                    {
                        l=y1;
                    }
                 
              }
              System.out.println(l);
              for(int check=130;check<x;check+=132)
              {
                  System.out.println("hiii"+check);
              category_list_panel.add(new DrawLine(l), new org.netbeans.lib.awtextra.AbsoluteConstraints(check,30,3,l+190));
              }  
              //JScrollPane scrollPane=new JScrollPane(category_panel);
              //scrollPane.setSize(430,290);
              //add(scrollPane);
              //getContentPane().add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 430, 390));
               //x.close();
        } catch (SQLException ex) {
            Logger.getLogger(Category.class.getName()).log(Level.SEVERE, null, ex);
        }
}
        
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        view_cat_panel1 = new javax.swing.JPanel();
        category_list_scrollpane = new javax.swing.JScrollPane();
        category_list_panel = new javax.swing.JPanel();
        category_label = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        view_cat_panel1.setBackground(new java.awt.Color(255, 255, 255));
        view_cat_panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        category_list_panel.setBackground(new java.awt.Color(153, 0, 153));
        category_list_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        category_list_scrollpane.setViewportView(category_list_panel);

        view_cat_panel1.add(category_list_scrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 420, 370));

        category_label.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        category_label.setForeground(new java.awt.Color(204, 0, 204));
        category_label.setText("Category");
        view_cat_panel1.add(category_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        getContentPane().add(view_cat_panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

int l=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel category_label;
    private javax.swing.JPanel category_list_panel;
    private javax.swing.JScrollPane category_list_scrollpane;
    private javax.swing.JPanel view_cat_panel1;
    // End of variables declaration//GEN-END:variables
}
