
import java.awt.Image;
import java.sql.Connection;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Customer_options extends javax.swing.JInternalFrame {

    /**
     * Creates new form Customer_options
     */
    Connection con;
    public Customer_options(Connection con) {
       
        initComponents();
        this.con=con;
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customer_options_panel = new javax.swing.JPanel();
        add_customer_icon = new javax.swing.JLabel();
        view_customer_icon = new javax.swing.JLabel();
        view_customer_label = new javax.swing.JLabel();
        add_customer_label = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customer_options_panel.setBackground(new java.awt.Color(255, 255, 255));
        customer_options_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        //new javax.swing.ImageIcon(getClass().getResource("/icons8_add_user_male_60px.png"))
        add_customer_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_add_user_male_60px.png"))); // NOI18N
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(getClass().getResource("/icons8_add_user_male_60px.png")).getImage().getScaledInstance(120,120, Image.SCALE_DEFAULT));
        add_customer_icon.setIcon(imageIcon);
        add_customer_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_customer_iconMouseClicked(evt);
            }
        });
        customer_options_panel.add(add_customer_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 120, 120));

        view_customer_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_group_60px.png"))); // NOI18N
        ImageIcon imageIcon1 = new ImageIcon(new ImageIcon(getClass().getResource("/icons8_group_60px.png")).getImage().getScaledInstance(120,120, Image.SCALE_DEFAULT));
        view_customer_icon.setIcon(imageIcon1);
        customer_options_panel.add(view_customer_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 120, 120));

        view_customer_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        view_customer_label.setForeground(new java.awt.Color(255, 51, 0));
        view_customer_label.setText("View Customers");
        customer_options_panel.add(view_customer_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));

        add_customer_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        add_customer_label.setForeground(new java.awt.Color(255, 51, 0));
        add_customer_label.setText("Add Customer");
        add_customer_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_customer_labelMouseClicked(evt);
            }
        });
        customer_options_panel.add(add_customer_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        getContentPane().add(customer_options_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void customers_add()
{
     Assistant_login.jDesktopPane1.removeAll();
        Add_Customer add_Customer=new Add_Customer(con);
        add_Customer.setVisible(true);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) add_Customer.getUI()).setNorthPane(null);

        add_Customer.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
          Assistant_login.jDesktopPane1.add(add_Customer);
}
    private void add_customer_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_customer_labelMouseClicked
        // TODO add your handling code here:
        customers_add();
    }//GEN-LAST:event_add_customer_labelMouseClicked

    private void add_customer_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_customer_iconMouseClicked
        // TODO add your handling code here:
        customers_add();
    }//GEN-LAST:event_add_customer_iconMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_customer_icon;
    private javax.swing.JLabel add_customer_label;
    private javax.swing.JPanel customer_options_panel;
    private javax.swing.JLabel view_customer_icon;
    private javax.swing.JLabel view_customer_label;
    // End of variables declaration//GEN-END:variables
}
